version: "3.0"
services:
    web-app:
        container_name: web-app
        image: web-app/latest
        restart: always
        build: ./App
        ports:
            - "5000:5000"
        networks:
            - common-net
    mongo-db:
        container_name: mongo-db
        image: mongo-db/latest
        build: ./Database
        volumes:
            - DatabasePersist:/data/db
        networks:
            - common-net
        ports:
            - '27017:27017'
            
networks:
    common-net:
volumes:
    DatabasePersist: